version = 1

exclude_patterns = [
  '**/examples/**'
]

[[transformers]]
    name = "prettier"
    enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "commonjs"
  environment = ["nodejs"]
  dependency_file_paths = [
  "app/"
  ]
  dialect = "typescript"
